services:
  backend:
    image: khalelam/ai_reviewer:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TLL=${REDIS_TTL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
