services:
  backend:
    image: khalelam/ai_reviewer:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
